### Post create transaction
POST http://localhost:8080/api/v1/transaction/account/2
Content-Type: application/json

{
  "move": false,
  "amount": 500,
  "description": "retire for something account 2",
  "dateTime": "2021-09-01"
}

### Put update transaction
PUT http://localhost:8080/api/v1/transaction/account/1
Content-Type: application/json

{
  "transactionId": 3,
  "move": false,
  "amount": 1000,
  "description": "retire for something more",
  "dateTime": "2021-09-01"
}

### Get transaction by Id
GET http://localhost:8080/api/v1/transaction/1

### Get all transactions
GET http://localhost:8080/api/v1/transaction

### Get transactions by Account Id
GET http://localhost:8080/api/v1/transaction/account/1

### Delete transaction by Id
DELETE http://localhost:8080/api/v1/transaction/3/account/1